### ISSUE TITLE
Print Problem in Document Editor

### ISSUE THREAD

**Issue by NirajVisana** [ckeditor/ckeditor4-docs-samples#17]
I have been trying to search for this issue from last whole week but unable to find any solution.

I have implemented CKEditor in one of old software but also with content I have to merge header and footer which is dynamic to the print preview of CKEditor.

I tried:

1. I have a button who called editor.execcommand('print') but it only prints content of text editor I can not merge my header and footer to the print

2. The second thing I tried is to redirect to a new page where I will prepare an HTML page with header and footer but I am not getting content correct line spacing and exact line to line words, I am attaching a screenshot here for the reference.

A pdf fro the same has to be generated but the same issue not getting the proper line to line content.

Data is coming from MySQL database I have checked the content that's perfectly fine, I think the issue is with sizes of text editor, HTML page and pdf but don't know how to solve this.

I can not share much code here but if anyone needs it let me know in the comment.

for pdf i am using dompdf.

i am trying to solve this issue from last week, i have serach many questions nothing maches my need so please do not make this as duplicate.

original content:

[
![original](https://user-images.githubusercontent.com/24972333/69241052-e6630a00-0bc3-11ea-879e-46d0f9f7c742.png)
](url)

print view:

![print](https://user-images.githubusercontent.com/24972333/69241072-f67ae980-0bc3-11ea-8082-2b34675d7607.png)

pdf view:

![pdf](https://user-images.githubusercontent.com/24972333/69241089-00045180-0bc4-11ea-9c37-5dbfb1e40325.png)

**Comment by Dumluregn** [comment]
Hello!
At first, please note that the place for this kind of issues is [ckeditor4 repo](https://github.com/ckeditor/ckeditor4/issues), so I will close this issue.
As for the issue itself, in version `4.14.0` (in March 2020) we introduced a new version of [print plugin](https://ckeditor.com/cke4/addon/print), so you could try it out. It provides a [contentPreview event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-contentPreview), which allows to modify data before printing, so you should be able to merge a header and footer.
