### ISSUE TITLE
 How to add this plugin to Angular's ckeditor?

### ISSUE THREAD

**Issue by pedrobcavalcante** [ckeditor/ckeditor4-docs-samples#22]
I'm having trouble to finding the right documentation to add the ckeditor4 autocomplete plugin to Angular. How do I add it?

**Comment by jacekbogdanski** [comment]
You can use [`config`](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#config) property including information about required plugins. Autocomplete plugin should be added to the required editor's plugins list. See [Installing Plugins](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_plugins.html) guide to learn more.
